const intOrFloat = '\\d+(\\.\\d+)?';  // Pattern to match integers or floats
const unitSuffix = '\\b'; // Word boundary to end the unit

const ingredients = [
    { name: 'almond meal', multiplier: 125 },
    { name: 'almonds', multiplier: 140 },
    { name: 'almonds, ground|ground almonds', multiplier: 100 },
    { name: 'almonds, slivered', multiplier: 108 },
    { name: 'amaranth', multiplier: 200 },
    { name: 'banana, mashed', multiplier: 250 },
    { name: 'banana, dried', multiplier: 115 },
    { name: 'banana, chips', multiplier: 70 },
    { name: 'barley', multiplier: 208 },
    { name: 'brazil nuts', multiplier: 140 },
    { name: 'bread flour', multiplier: 136 },
    { name: 'breadcrumbs', multiplier: 150 },
    { name: 'broccoli flowerets', multiplier: 71 },
    { name: 'buckwheat, grain', multiplier: 200 },
    { name: 'butter|unsalted butter|melted butter|lightly salted butter', multiplier: 227 },
    { name: 'butternut, chopped', multiplier: 150 },
    { name: 'cacao nibs', multiplier: 130 },
    { name: 'canned pumpkin puree', multiplier: 220 },
    { name: 'canned chickpeas', multiplier: 240 },
    { name: 'canned beans|canned black beans|canned pinto beans', multiplier: 252 },
    { name: 'caster sugar', multiplier: 189.5 },
    { name: 'cashew', multiplier: 135 },
    { name: 'carrot, grated', multiplier: 70 },
    { name: 'chia|chia seeds', multiplier: 170 },
    { name: 'chia, milled', multiplier: 90 },
    { name: 'chickpeas, dried|dried chickpeas', multiplier: 200 },
    { name: 'chocolate chips', multiplier: 160 },
    { name: 'chopped walnuts', multiplier: 120 },
    { name: 'chopped pecans', multiplier: 120 },
    { name: 'chopped cashew nuts', multiplier: 160 },
    { name: 'cocoa|cocoa powder|unsweetened cocoa powder', multiplier: 125 },
    { name: 'cocoa nibs', multiplier: 120 },
    { name: 'coconut sugar', multiplier: 140 },
    { name: 'confectioners sugar|confectioners\' sugar|icing sugar|powdered sugar', multiplier: 132.73 },
    { name: 'cornstarch|corn starch', multiplier: 120 },
    { name: 'cottage cheese', multiplier: 226 },
    { name: 'couscous', multiplier: 180 },
    { name: 'cream|whipping cream|heavy cream', multiplier: 240 },
    { name: 'cream cheese', multiplier: 225 },
    { name: 'creme fraiche', multiplier: 240 },
    { name: 'dates, pitted', multiplier: 140 },
    { name: 'dates, Medjools', multiplier: 150 },
    { name: 'demerera sugar', multiplier: 220 },
    { name: 'desiccated coconut', multiplier: 80 },
    { name: 'dried apples', multiplier: 120 },
    { name: 'flaked almonds', multiplier: 85 },
    { name: 'flaked coconut', multiplier: 75 },
    { name: 'flax, milled', multiplier: 110 },
    { name: 'flax, ground|ground flaxseeds', multiplier: 148 },
    { name: 'flour|all-purpose flour|all purpose flour', multiplier: 125 },
    { name: 'frozen peas', multiplier: 140 },
    { name: 'greek yogurt', multiplier: 228 },
    { name: 'hazelnuts', multiplier: 135 },
    { name: 'honey|molasses|syrup|light corn syrup|corn syrup', multiplier: 340 },
    { name: 'jaggery', multiplier: 130 },
    { name: 'kidney beans|red kidney beans', multiplier: 180 },
    { name: 'lentils, puy|puy lentils', multiplier: 210 },
    { name: 'lentils, red|red lentils', multiplier: 190 },
    { name: 'light brown sugar, packed', multiplier: 220 },
    { name: 'light brown sugar', multiplier: 150 },
    { name: 'margarine', multiplier: 230 },
    { name: 'macadamia', multiplier: 140 },
    { name: 'maple syrup', multiplier: 322 },
    { name: 'mascarpone', multiplier: 240 },
    { name: 'milled seeds', multiplier: 120 },
    { name: 'millet, flakes', multiplier: 115 },
    { name: 'milk|warm milk|whole milk', multiplier: 244.87 },
    { name: 'nutritional yeast', multiplier: 40 },
    { name: 'nut butter', multiplier: 270 },
    { name: 'nuts, chopped|chopped nuts', multiplier: 150 },
    { name: 'nuts, ground', multiplier: 120 },
    { name: 'oatmeal', multiplier: 175 },
    { name: 'oats', multiplier: 90 },
    { name: 'packed brown sugar', multiplier: 220 },
    { name: 'parmesan (finely grated)|grated Parmesan', multiplier: 80 },
    { name: 'pasta', multiplier: 120 },
    { name: 'peanuts chopped', multiplier: 150 },
    { name: 'Philadelphia cream cheese', multiplier: 250 },
    { name: 'pistachio|pistachios', multiplier: 135 },
    { name: 'pine nuts', multiplier: 140 },
    { name: 'pumpkin seeds', multiplier: 135 },
    { name: 'polenta (fine)|polenta, fine', multiplier: 135 },
    { name: 'poppy seeds', multiplier: 144 },
    { name: 'potato, mashed', multiplier: 200 },
    { name: 'pineapple, chopped', multiplier: 150 },
    { name: 'prunes', multiplier: 180 },
    { name: 'poppy seeds', multiplier: 144 },
    { name: 'pumpkin seeds', multiplier: 128 },
    { name: 'quinoa|dry quinoa', multiplier: 200 },
    { name: 'raisins', multiplier: 165 },
    { name: 'raw sugar', multiplier: 250 },
    { name: 'rice|white rice', multiplier: 178.15 },
    { name: 'ricotta cheese', multiplier: 248 },
    { name: 'rolled oats', multiplier: 85 },
    { name: 'sesame', multiplier: 140 },
    { name: 'sliced almonds', multiplier: 80 },
    { name: 'slivered almonds', multiplier: 80 },
    { name: 'sour cream', multiplier: 240 },
    { name: 'stevia erylite', multiplier: 200 },
    { name: 'strawberries', multiplier: 165 },
    { name: 'sugar|white sugar|granulated sugar|brown sugar|organic sugar|dark brown sugar|light sugar|golden sugar', multiplier: 201 },
    { name: 'superfine sugar', multiplier: 225 },
    { name: 'sultanas', multiplier: 200 },
    { name: 'sunflower seeds', multiplier: 140 },
    { name: 'sweet potato, chopped', multiplier: 150 },
    { name: 'sweetened condensed milk', multiplier: 306 },
    { name: 'table salt', multiplier: 300 },
    { name: 'tomato paste', multiplier: 220 },
    { name: 'vegetable shortening', multiplier: 190 },
    { name: 'walnuts', multiplier: 120 },
    { name: 'water|warm water|boiling water', multiplier: 240 },
    { name: 'white granulated sugar', multiplier: 220 },
    { name: 'wine|red wine|white wine', multiplier: 240 },
    { name: 'yeast', multiplier: 148.8 },
    { name: 'yogurt', multiplier: 245 }
];

// Generate regex patterns for each ingredient
export const cookingUnitsCheckForConversion = ingredients.map(ingredient => ({
    regex: new RegExp('(' + intOrFloat + ' ?cup ?' + ingredient.name + ')' + unitSuffix, 'ig'),
    unit: 'g',
    multiplier: ingredient.multiplier
}));

// Cup, tablespoon, or teaspoon